version: "3.8"

services:
  dvwa:
    image: vulnerables/web-dvwa
    ports:
      - "8080:80"
    environment:
      - RECAPTCHA_PRIV_KEY=
      - RECAPTCHA_PUB_KEY=
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/login.php"]
      interval: 10s
      timeout: 5s
      retries: 10

  juiceshop:
    image: bkimminich/juice-shop
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 10s
      timeout: 5s
      retries: 10
