# Copyright (c) 2026 M. TENDENG
# Licensed under the MIT License. See LICENSE file for details.

"""
WAF Detector : identifie la présence et le type de WAF/CDN depuis les réponses HTTP.

Résultats stockés dans EndpointNode.detected_waf et ApplicationModel._tech_stack
sous la forme "waf:cloudflare", "waf:modsecurity", etc.

Ces tags déclenchent l'encoding_pipeline adaptatif dans ExperimentEngine.
"""
from __future__ import annotations

import re
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from hdwp.core.model.schemas import RawObservation

# ── Signatures WAF ────────────────────────────────────────────────────────────

_WAF_SIGNATURES: dict[str, list[tuple[str, re.Pattern]]] = {
    "waf:cloudflare": [
        ("header_name", re.compile(r"cf-ray", re.I)),
        ("header_value", re.compile(r"cloudflare", re.I)),
        ("body", re.compile(r"cloudflare|Attention Required.*Cloudflare", re.I)),
        ("header_value", re.compile(r"server.*cloudflare", re.I)),
    ],
    "waf:modsecurity": [
        ("header_name", re.compile(r"mod_security|modsecurity", re.I)),
        ("header_value", re.compile(r"mod_security|modsecurity", re.I)),
        ("body", re.compile(r"ModSecurity.*Web Application Firewall|This error was generated by Mod_Security", re.I)),
    ],
    "waf:akamai": [
        ("header_name", re.compile(r"x-check-cacheable|akamaighost", re.I)),
        ("header_value", re.compile(r"akamai", re.I)),
        ("body", re.compile(r"Reference #\d+\.\d+\.\d+\.\d+", re.I)),
    ],
    "waf:aws_waf": [
        ("body", re.compile(r"AWS WAF|Request blocked by AWS WAF", re.I)),
        ("header_name", re.compile(r"x-amzn-requestid|x-amz-cf-id", re.I)),
    ],
    "waf:f5_bigip": [
        ("header_name", re.compile(r"bigipserver|x-cnection", re.I)),
        ("header_value", re.compile(r"bigip|tmui", re.I)),
        ("body", re.compile(r"The requested URL was rejected\. Please consult with your administrator", re.I)),
    ],
    "waf:imperva": [
        ("header_name", re.compile(r"x-iinfo|x-cdn", re.I)),
        ("header_value", re.compile(r"incapsula", re.I)),
        ("body", re.compile(r"incident_id|incap_ses|_Incapsula_Resource", re.I)),
    ],
    "waf:barracuda": [
        ("body", re.compile(r"Barracuda Web Application Firewall|barra_counter_session", re.I)),
    ],
    "waf:sucuri": [
        ("header_value", re.compile(r"sucuri", re.I)),
        ("body", re.compile(r"Sucuri WebSite Firewall|sucuri-gui", re.I)),
    ],
    "waf:nginx_limit": [
        ("body", re.compile(r"<html>\s*<head><title>403 Forbidden</title>.*nginx", re.I | re.S)),
    ],
    "waf:generic": [
        ("body", re.compile(
            r"access denied|blocked by.*security|web application firewall|"
            r"your request has been blocked|security violation detected",
            re.I
        )),
    ],
}

# Réponses 403 pures sans corps sont souvent des rate-limits ou règles réseau
_BARE_403_MIN_BODY = 50  # bytes minimum pour tenter la détection


def detect_waf(obs: RawObservation) -> str | None:
    """Retourne le tag WAF détecté ("waf:cloudflare") ou None si aucun WAF reconnu.

    Appelé sur les réponses 403/406/429 pour identifier la présence d'un WAF.
    """
    if obs.response is None:
        return None

    status = obs.response.status_code
    if status not in (403, 406, 429, 503):
        return None

    headers = {k.lower(): v.lower() for k, v in (obs.response.headers or {}).items()}
    body_str = str(obs.response.body or "").lower()

    # Ne pas tenter la détection si le body est trop court (bare 403)
    if len(body_str) < _BARE_403_MIN_BODY and "waf:generic" not in _WAF_SIGNATURES:
        return None

    for waf_tag, patterns in _WAF_SIGNATURES.items():
        if waf_tag == "waf:generic":
            continue  # tester le générique en dernier
        for source, pattern in patterns:
            if source == "header_name":
                if any(pattern.search(k) for k in headers):
                    return waf_tag
            elif source == "header_value":
                if any(pattern.search(v) for v in headers.values()):
                    return waf_tag
            elif source == "body":
                if pattern.search(body_str):
                    return waf_tag

    # Générique en dernier recours
    for source, pattern in _WAF_SIGNATURES.get("waf:generic", []):
        if source == "body" and pattern.search(body_str):
            return "waf:generic"

    return None
